#!/usr/bin/env bash

#### Beschrijving : Dit is een bash script om de  commando's die nodig zijn om je systeem up te daten te automatiseren
####  Geschreven door Bilal Achahbar op 14/02/2018

sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade